/* v3.0 frontend build — BUILD-TIME ONLY (never runs at engine runtime).
 *
 * Two jobs:
 *   1. Vendor the runtime deps from node_modules → static/vendor/ (React prod
 *      UMD, ECharts 5.5.1, GridStack js+css, the two fonts as local woff2 +
 *      @font-face css). Drops every CDN dependency — offline/localhost doctrine.
 *   2. esbuild-transform each JSX module under src/ (classic React.createElement,
 *      NO bundling — the modules share via window globals, exactly as the
 *      reference loaded them as separate <script> tags) and CONCATENATE in the
 *      fixed load order into one content-hashed bundle static/v3/app.<hash>.js.
 *      tokens.css + shell.css are emitted with the same build hash so a rebuild
 *      changes their FILENAMES, not just a query string — the root-scoped,
 *      cache-first service worker (base.html registers it at scope '/', so it
 *      intercepts /static/* even though /v3 registers none of its own) can
 *      therefore never stale-serve the app bundle or its CSS. CAVEAT: the
 *      vendored /static/vendor/* deps keep STABLE filenames, so a same-name
 *      re-vendor could be served stale by that SW until CACHE_NAME bumps —
 *      scoping /v3 away from the root SW (or hashing the vendored files) is
 *      deferred coexistence work (plan §1.4/§1.5).
 *
 * The build OUTPUT (static/v3/, static/vendor/) is committed; node_modules is
 * gitignored. Run: `npm run build` (from frontend/).
 */
import { transform } from 'esbuild';
import vm from 'node:vm';
import { createHash } from 'node:crypto';
import { readFile, writeFile, copyFile, mkdir, rm, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));           // frontend/
const ROOT = dirname(HERE);                                     // repo root
const SRC = join(HERE, 'src');
const NM = join(HERE, 'node_modules');
const V3 = join(ROOT, 'static', 'v3');
const VENDOR = join(ROOT, 'static', 'vendor');
const FONTS = join(VENDOR, 'fonts');

/* ── JSX load order ───────────────────────────────────────────────────────
 * ORDER IS LOAD-BEARING (modules read each other's globals). This is the P0
 * shared-foundation subset; page phases (P1–P7) APPEND their modules here,
 * before app-shell.jsx which must stay LAST (it calls ReactDOM.createRoot).
 * Mirrors docs/design/meridian_v3/Meridian v3.0.html:106-125. */
const JSX_ORDER = [
  'primitives.jsx',
  'charts.jsx',
  'grid-workspace.jsx',
  'nav-and-data.jsx',
  'notifications.jsx',
  'sse-adapter.js',           // SSE client-adapter skeleton (§1.2)
  'dash-tiled.jsx',           // P1 — Dashboard page (wired to snapshot + SSE)
  'pages-config.jsx',         // P2 — Config page (accounts/connections/presets/system)
  // ── remaining page modules land here in their phases (pages, models, …) ──
  'app-shell.jsx',            // MUST be last
];

/* Fonts vendored from @fontsource (latin, weights 400/500/600/700). */
const FONT_FACES = [
  { family: 'Space Grotesk', pkg: 'space-grotesk', weights: [400, 500, 600, 700] },
  { family: 'JetBrains Mono', pkg: 'jetbrains-mono', weights: [400, 500, 600, 700] },
];

async function freshDir(p) {
  if (existsSync(p)) await rm(p, { recursive: true, force: true });
  await mkdir(p, { recursive: true });
}

async function vendorDeps() {
  await freshDir(VENDOR);
  await mkdir(FONTS, { recursive: true });

  const copies = [
    [join(NM, 'react', 'umd', 'react.production.min.js'), join(VENDOR, 'react.production.min.js')],
    [join(NM, 'react-dom', 'umd', 'react-dom.production.min.js'), join(VENDOR, 'react-dom.production.min.js')],
    [join(NM, 'echarts', 'dist', 'echarts.min.js'), join(VENDOR, 'echarts.min.js')],
    [join(NM, 'gridstack', 'dist', 'gridstack-all.js'), join(VENDOR, 'gridstack-all.js')],
    [join(NM, 'gridstack', 'dist', 'gridstack.min.css'), join(VENDOR, 'gridstack.min.css')],
  ];
  for (const [from, to] of copies) {
    if (!existsSync(from)) throw new Error(`vendor source missing: ${from} (run npm install)`);
    await copyFile(from, to);
  }

  // Fonts: copy woff2 + synthesize a local @font-face sheet.
  const faceRules = [];
  for (const { family, pkg, weights } of FONT_FACES) {
    for (const w of weights) {
      const file = `${pkg}-latin-${w}-normal.woff2`;
      const from = join(NM, '@fontsource', pkg, 'files', file);
      if (!existsSync(from)) throw new Error(`font source missing: ${from}`);
      await copyFile(from, join(FONTS, file));
      faceRules.push(
        `@font-face{font-family:'${family}';font-style:normal;font-weight:${w};` +
        `font-display:swap;src:url('/static/vendor/fonts/${file}') format('woff2');}`
      );
    }
  }
  const fontsCss =
    `/* v3.0 vendored fonts — Space Grotesk + JetBrains Mono (latin, 400/500/600/700).\n` +
    `   Generated by frontend/build.mjs from @fontsource. Replaces the Google Fonts CDN link. */\n` +
    faceRules.join('\n') + '\n';
  await writeFile(join(VENDOR, 'fonts', 'fonts.css'), fontsCss, 'utf8');

  return copies.map(([, to]) => to).concat([join(FONTS, 'fonts.css')]);
}

async function buildBundle() {
  const parts = [
    `/* v3.0 app bundle — precompiled from frontend/src/ by build.mjs.\n` +
    `   DO NOT EDIT: regenerate with \`npm run build\`. Concatenated modules share\n` +
    `   window globals in load order (classic React.createElement). */\n`,
  ];
  for (const name of JSX_ORDER) {
    const path = join(SRC, name);
    if (!existsSync(path)) throw new Error(`JSX source missing: ${path}`);
    const code = await readFile(path, 'utf8');
    const out = await transform(code, {
      loader: 'jsx',
      jsx: 'transform',
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      target: 'es2019',
      sourcefile: name,
    });
    parts.push(`\n/* ==== ${name} ==== */\n`, out.code, '\n;\n');
  }
  return parts.join('');
}

async function main() {
  const t0 = Date.now();
  const vendored = await vendorDeps();

  const bundleJs = await buildBundle();

  // Fail-loud parse guardrail (plan §1.6 / L3·Finding 8): esbuild transforms
  // each module INDEPENDENTLY, so a cross-module collision (a duplicate
  // top-level const/let/class once page phases append modules) or any defect
  // spanning the concatenation join is invisible per-file and would only
  // blank-page in the browser. Compile the whole concatenated bundle here so it
  // becomes a BUILD failure instead.
  try {
    new vm.Script(bundleJs, { filename: 'app.bundle.js' });
  } catch (e) {
    throw new Error(`concatenated bundle failed to parse: ${e.message}`);
  }

  const tokensCss = await readFile(join(SRC, 'tokens.css'), 'utf8');
  const shellCss = await readFile(join(SRC, 'shell.css'), 'utf8');

  const hash = createHash('sha256')
    .update(bundleJs).update(tokensCss).update(shellCss)
    .digest('hex').slice(0, 10);

  await freshDir(V3);
  const appName = `app.${hash}.js`;
  const tokensName = `tokens.${hash}.css`;
  const shellName = `shell.${hash}.css`;
  await writeFile(join(V3, appName), bundleJs, 'utf8');
  await writeFile(join(V3, tokensName), tokensCss, 'utf8');
  await writeFile(join(V3, shellName), shellCss, 'utf8');

  const manifest = {
    hash,
    app: appName,
    tokens: tokensName,
    shell: shellName,
    modules: JSX_ORDER,
    note: 'Generated by frontend/build.mjs — do not edit by hand.',
  };
  await writeFile(join(V3, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  const kb = (n) => (Buffer.byteLength(n, 'utf8') / 1024).toFixed(1) + ' KB';
  console.log('[v3 build] hash', hash, 'in', Date.now() - t0, 'ms');
  console.log('  static/v3/' + appName, kb(bundleJs));
  console.log('  static/v3/' + tokensName, kb(tokensCss));
  console.log('  static/v3/' + shellName, kb(shellCss));
  console.log('  vendored →', vendored.length, 'files under static/vendor/');
}

main().catch((e) => {
  console.error('[v3 build] FAILED:', e.message);
  process.exit(1);
});
