-- migration: per_account
-- name: 013_v2_5_pretrade_regime_stale
-- description: Persist the regime_stale decision flag at plan time
--              (Task 165, T157 follow-up).

-- Task 157 (migration 011) added regime_label / regime_multiplier /
-- regime_mode / apply_regime_multiplier so the live engine's exact
-- sizing decision is recoverable. It deliberately omitted the
-- `regime_stale` flag (calc dict carries it via risk_engine.py:655)
-- because at the time the stale-fallback policy "stale → mult 1.0"
-- was reconstructible from `regime.is_stale` re-derivation against the
-- pre_trade_log timestamp + the recorded multiplier.
--
-- Task 165 (regime build 1b) made that reconstruction unreliable for
-- two reasons:
--   1. config.REGIME_STALE_MINUTES is operator-tunable; a future
--      change would silently retro-invalidate past staleness reads.
--   2. With asymmetric hysteresis live, a transition that was
--      genuinely held during a stale window cannot be told apart from
--      one that flipped just before the read; the stored multiplier
--      alone doesn't disambiguate.
--
-- Persisting the stale flag at plan time pins the engine's view of
-- "was the macro read fresh?" to each row, so forward-analytics never
-- has to re-derive it from now-mutable config.
--
-- Schema:
--   • regime_stale INTEGER (SQLite has no bool). 0/1/NULL — NULL
--     marks pre-T165 rows where the flag wasn't captured. Same
--     "NULL = unknown, never coerce to a default" discipline as
--     migration 011.
--
-- Additive-only: existing rows keep all prior column values, gain a
-- NULL on regime_stale.

ALTER TABLE pre_trade_log ADD COLUMN regime_stale INTEGER;
